FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as poetry-builder

RUN microdnf -y update && \
    microdnf -y install \
        git shadow-utils python3.12-pip python-wheel \
        gcc python3.12-devel && \
    pip3.12 install --no-cache-dir --upgrade pip wheel && \
    microdnf clean all

ENV POETRY_VIRTUALENVS_IN_PROJECT=1

WORKDIR /caikit
COPY pyproject.toml .
COPY poetry.lock .
RUN pip3.12 install poetry && poetry install --no-root
#RUN pip3.12 install poetry && poetry env use /usr/bin/python3.12 && poetry install --no-root

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as deploy
RUN microdnf -y update && \
    microdnf -y install \
        shadow-utils python3.12 && \
    microdnf clean all

WORKDIR /caikit

COPY --from=poetry-builder /caikit/.venv /caikit/.venv
COPY caikit.yml /caikit/config/caikit.yml

ENV VIRTUAL_ENV=/caikit/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN /caikit/.venv/bin/pip install --no-cache-dir \
    "urllib3>=2.7.0" "fastapi>=0.134.0" "starlette>=1.3.1" "aiohttp>=3.14.3,<4.0.0" "python-dotenv==1.2.2" "ujson>=5.12.1"

RUN groupadd --system caikit --gid 1001 && \
    adduser --system --uid 1001 --gid 0 --groups caikit \
    --create-home --home-dir /caikit --shell /sbin/nologin \
    --comment "Caikit User" caikit

USER caikit

ENV CONFIG_FILES=/caikit/config/caikit.yml
VOLUME ["/caikit/config/"]

CMD ["python",  "-m", "caikit.runtime"]

LABEL name="rhoai/odh-caikit-tgis-serving-rhel9" \
      com.redhat.component="odh-caikit-tgis-serving-rhel9" \
      io.k8s.display-name="odh-caikit-tgis-serving-rhel9" \
      io.k8s.description="Caikit-TGIS-Serving is a stack that allows data scientists to perform Large Language Model (LLM) inference." \
      description="Caikit-TGIS-Serving is a stack that allows data scientists to perform Large Language Model (LLM) inference." \
      summary="Caikit-TGIS-Serving is a stack that allows data scientists to perform Large Language Model (LLM) inference." \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
